from modules.cashier import Cashier
from modules.struct import User, Item
from modules.promotion import Promotion
from modules.mocked_systems import VIPSystem, PaymentSystem

if __name__ == "__main__":
    item1 = Item(itemID="00001", itemName='苹果', itemPrice=2, itemUnits=10)
    item2 = Item(itemID="00002", itemName='橘子', itemPrice=3, itemUnits=5)
    item3 = Item(itemID="00003", itemName='苹果手机', itemPrice=5000, itemUnits=1)

    regularUser = User(userID="REGULAR001")
    vipUser = User(userID="VIP001", VIPCardNum="VIP001")

    vipSystem = VIPSystem()
    paymentSystem = PaymentSystem()
    cashier = Cashier(vipSystem, paymentSystem)

    print("------Regular user under 200------")
    order = cashier.checkout(item1, item2, user=regularUser)
    print(f"\tPurchased items: {order.items}")
    print(f"\tTotal items: {order.totalItems}")
    print(f"\tTotal amount due before discount: {order.amountDueBeforeDiscount}")
    print(f"\tTotal amount due after discount: {order.amountDue}")
    print(f"\tPromotion applied: {order.promotionApplied}")
    print(f"\tMoney paid: {60}, Money change: {cashier.pay(order, 60)}")
    print()
    print("------Regular user above 200------")
    order = cashier.checkout(item1, item3, user=regularUser)
    print(f"\tPurchased items: {order.items}")
    print(f"\tTotal items: {order.totalItems}")
    print(f"\tTotal amount due before discount: {order.amountDueBeforeDiscount}")
    print(f"\tTotal amount due after discount: {order.amountDue}")
    print(f"\tPromotion applied: {order.promotionApplied}")
    print(f"\tMoney paid: {60}, Money change: {cashier.pay(order, 60)}")
    print()
    print("------VIP user under 200 and less than 10 items------")
    order = cashier.checkout(item2, user=vipUser)
    print(f"\tPurchased items: {order.items}")
    print(f"\tTotal items: {order.totalItems}")
    print(f"\tTotal amount due before discount: {order.amountDueBeforeDiscount}")
    print(f"\tTotal amount due after discount: {order.amountDue}")
    print(f"\tPromotion applied: {order.promotionApplied}")
    print(f"\tMoney paid: {60}, Money change: {cashier.pay(order, 60)}")
    print()
    print("------VIP user above 200 and less than 10 items------")
    order = cashier.checkout(item2, item3, user=vipUser)
    print(f"\tPurchased items: {order.items}")
    print(f"\tTotal items: {order.totalItems}")
    print(f"\tTotal amount due before discount: {order.amountDueBeforeDiscount}")
    print(f"\tTotal amount due after discount: {order.amountDue}")
    print(f"\tPromotion applied: {order.promotionApplied}")
    print(f"\tMoney paid: {60}, Money change: {cashier.pay(order, 60)}")
    print()
    print("------VIP user above 200 and more than 10 items------")
    order = cashier.checkout(item1, item2, item3, user=vipUser)
    print(f"\tPurchased items: {order.items}")
    print(f"\tTotal items: {order.totalItems}")
    print(f"\tTotal amount due before discount: {order.amountDueBeforeDiscount}")
    print(f"\tTotal amount due after discount: {order.amountDue}")
    print(f"\tPromotion applied: {order.promotionApplied}")
    print(f"\tMoney paid: {60}, Money change: {cashier.pay(order, 60)}")
    print()
